version: '3.9'

services:
  cache:
    image: redis:6.2-alpine
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  mongodb:
    image: mongo:6-jammy
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

volumes:
  dbdata: